### ISSUE TITLE
add Recall example to README??

### ISSUE THREAD

**Issue by rmflight** [dirkschumacher/rcompilertools#1]
I'm guessing [this tweet](https://twitter.com/dirk_sch/status/1454484838455595019) code was making use of this package for the ability to do infinite recursion.

It would be awesome if the "Recall" function definition and the tweeted example was part of the README file ...

Given that I can find GOTO.ops in the tibble of bytecode operators returned by `opcodes`, I can *start* to see how that might be constructed, but it would be awesome to have a worked example.

**Comment by dirkschumacher** [comment]
I published the code as a package: https://github.com/dirkschumacher/notail does that help?

**Comment by rmflight** [comment]
It does Dirk, thank you very much.

**Comment by dirkschumacher** [comment]
Happy hacking 🤓
